server:
  port: 8082
spring:
  application:
    name: platform
  cloud:
    nacos:
      server-addr: http://43.136.108.55:8848 # nacos服务的地址
#      discovery:
#        ip: 47.106.221.17 #自行配置注冊到nacos的ip地址
#  datasource:
#    url: jdbc:mysql://47.106.221.17:3306/my_system?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      pool-name: demo
#      minimum-idle: 5
#      idle-timeout: 120000
#      max-lifetime: 120000
#      maximum-pool-size: 30
#      connection-timeout: 6000
#      connection-test-query: select 1
#  data:
#    mongodb:
      #      host: 43.136.108.55
      #      port: 27017
      #      database: platform-data
      #      username: api
      #      password: root123
#      uri: mongodb://api:root123@43.136.108.55:27017/platform-data?authSource=admin
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:com/mysystem/dao/mapper/*.xml